refactored bind providers
neos/ldap pull request #11
Opened 2017-01-17 18:20 UTC by fschwaiger

- moved common code to `AbstractBindProvider`
- renamed `getFilteredUsername()` to `filterUsername()` since it transforms input and is no getter
- simplified cases in `LdapBind`
- added doc

2017-01-17 19:27 UTC, radmiraal requested changes
Thanks! Aweomse PR, at first sight fixes a lot of the complexity in the binding. Will give it a more close look soonish.

Just added some minor cgl nitpicks, regarding the whitespace on empty line: many IDE's can auto strip whitespace on end of lines on save.
I hope you don't mind I add those nitpicks, but have no idea how familiar you are with the cgl ;)

2017-01-17 19:27 UTC, radmiraal commented on Classes/Service/BindProvider/BindProviderInterface.php
> +
nitpick: whitespace

2017-01-17 19:27 UTC, radmiraal commented on Classes/Service/BindProvider/LdapBind.php
> +        }
cgl nitpick: elseif should be one the same line as the closing curly brace

2017-01-19 13:49 UTC, kdambekalns reviewed
Looks good to me, purely from reading.

2017-02-28 11:24 UTC, merged